// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type DatasetAddress struct {
	DatasetNo    int64
	NoOfCommands int64
	Address      int64
}

type DatasetDetail struct {
	DatasetNo   int64
	Details     string
	LinkedMacro int64
	Description string
}

type MacroAddress struct {
	MacroNo      int64
	NoOfCommands int64
	Address      int64
}

type MacroDetail struct {
	MacroNo int64
	Details string
}

type MacroRelatedTC struct {
	ID                int64
	MacroUpdate       string
	DatasetUpdate     string
	MacroEnable       string
	MacroInit         string
	MasterMacroEnable string
}

type Telecommand struct {
	CommandID string
	Mnemonics string
	Code      string
	Type      string
}
