// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
)

const clearDatasetAddress = `-- name: ClearDatasetAddress :exec
Delete from "DatasetAddresses"
`

func (q *Queries) ClearDatasetAddress(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDatasetAddress)
	return err
}

const clearDatasetDetails = `-- name: ClearDatasetDetails :exec
;

Delete from "DatasetDetails" where "DatasetNo" = ?
`

func (q *Queries) ClearDatasetDetails(ctx context.Context, datasetno int64) error {
	_, err := q.db.ExecContext(ctx, clearDatasetDetails, datasetno)
	return err
}

const clearMacroAddress = `-- name: ClearMacroAddress :exec
Delete from "MacroAddresses"
`

func (q *Queries) ClearMacroAddress(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMacroAddress)
	return err
}

const clearMacroDetails = `-- name: ClearMacroDetails :exec
Delete from "MacroDetails" where "MacroNo" = ?
`

func (q *Queries) ClearMacroDetails(ctx context.Context, macrono int64) error {
	_, err := q.db.ExecContext(ctx, clearMacroDetails, macrono)
	return err
}

const clearTelecommands = `-- name: ClearTelecommands :exec
Delete from "Telecommands"
`

func (q *Queries) ClearTelecommands(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTelecommands)
	return err
}

const getAllDatasets = `-- name: GetAllDatasets :many
Select "DatasetNo"  from "DatasetAddresses"
`

func (q *Queries) GetAllDatasets(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAllDatasets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var DatasetNo int64
		if err := rows.Scan(&DatasetNo); err != nil {
			return nil, err
		}
		items = append(items, DatasetNo)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMacros = `-- name: GetAllMacros :many
Select "MacroNo"  from "MacroAddresses"
`

func (q *Queries) GetAllMacros(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAllMacros)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var MacroNo int64
		if err := rows.Scan(&MacroNo); err != nil {
			return nil, err
		}
		items = append(items, MacroNo)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTCMnemonics = `-- name: GetAllTCMnemonics :many
Select "Mnemonics" from "Telecommands"
`

func (q *Queries) GetAllTCMnemonics(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllTCMnemonics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var Mnemonics string
		if err := rows.Scan(&Mnemonics); err != nil {
			return nil, err
		}
		items = append(items, Mnemonics)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommandCode = `-- name: GetCommandCode :one
Select "Code" from "Telecommands" where "Mnemonics" = ? Limit 1
`

func (q *Queries) GetCommandCode(ctx context.Context, mnemonics string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCommandCode, mnemonics)
	var Code string
	err := row.Scan(&Code)
	return Code, err
}

const getCommandType = `-- name: GetCommandType :one
;

Select "Type" from "Telecommands" where "Mnemonics" = ? Limit 1
`

func (q *Queries) GetCommandType(ctx context.Context, mnemonics string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCommandType, mnemonics)
	var Type string
	err := row.Scan(&Type)
	return Type, err
}

const getCompletedMacroDetails = `-- name: GetCompletedMacroDetails :many
;

Select "LinkedMacro", "DatasetNo", "Description" from "DatasetDetails"
`

type GetCompletedMacroDetailsRow struct {
	LinkedMacro int64
	DatasetNo   int64
	Description string
}

func (q *Queries) GetCompletedMacroDetails(ctx context.Context) ([]GetCompletedMacroDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedMacroDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletedMacroDetailsRow
	for rows.Next() {
		var i GetCompletedMacroDetailsRow
		if err := rows.Scan(&i.LinkedMacro, &i.DatasetNo, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatasetAddress = `-- name: GetDatasetAddress :one
Select "Address" from "DatasetAddresses" where "DatasetNo" = ? Limit 1
`

func (q *Queries) GetDatasetAddress(ctx context.Context, datasetno int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDatasetAddress, datasetno)
	var Address int64
	err := row.Scan(&Address)
	return Address, err
}

const getDatasetDetails = `-- name: GetDatasetDetails :one
Select DatasetNo, Details, LinkedMacro, Description from "DatasetDetails"
where "DatasetNo" = ? Limit 1
`

func (q *Queries) GetDatasetDetails(ctx context.Context, datasetno int64) (DatasetDetail, error) {
	row := q.db.QueryRowContext(ctx, getDatasetDetails, datasetno)
	var i DatasetDetail
	err := row.Scan(
		&i.DatasetNo,
		&i.Details,
		&i.LinkedMacro,
		&i.Description,
	)
	return i, err
}

const getDatasetNosBasedOnMacroType = `-- name: GetDatasetNosBasedOnMacroType :many
Select "DatasetNo" from "DatasetAddresses" where "NoOfCommands" is 
(Select "NoOfCommands" from "MacroAddresses" where "MacroNo"  = ?)
`

func (q *Queries) GetDatasetNosBasedOnMacroType(ctx context.Context, macrono int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getDatasetNosBasedOnMacroType, macrono)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var DatasetNo int64
		if err := rows.Scan(&DatasetNo); err != nil {
			return nil, err
		}
		items = append(items, DatasetNo)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDescriptionForDataset = `-- name: GetDescriptionForDataset :one
Select "Description" from "DatasetDetails" where "DatasetNo" = ? Limit 1
`

func (q *Queries) GetDescriptionForDataset(ctx context.Context, datasetno int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getDescriptionForDataset, datasetno)
	var Description string
	err := row.Scan(&Description)
	return Description, err
}

const getMacNoDSNoBasedOnDescription = `-- name: GetMacNoDSNoBasedOnDescription :one
Select "DatasetNo", "LinkedMacro" from "DatasetDetails" where "Description" = ? Limit 1
`

type GetMacNoDSNoBasedOnDescriptionRow struct {
	DatasetNo   int64
	LinkedMacro int64
}

func (q *Queries) GetMacNoDSNoBasedOnDescription(ctx context.Context, description string) (GetMacNoDSNoBasedOnDescriptionRow, error) {
	row := q.db.QueryRowContext(ctx, getMacNoDSNoBasedOnDescription, description)
	var i GetMacNoDSNoBasedOnDescriptionRow
	err := row.Scan(&i.DatasetNo, &i.LinkedMacro)
	return i, err
}

const getMacroAddress = `-- name: GetMacroAddress :one
Select "Address" from "MacroAddresses" where "MacroNo" = ? Limit 1
`

func (q *Queries) GetMacroAddress(ctx context.Context, macrono int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMacroAddress, macrono)
	var Address int64
	err := row.Scan(&Address)
	return Address, err
}

const getMacroDetails = `-- name: GetMacroDetails :one
;

Select MacroNo, Details from "MacroDetails"
where "MacroNo" = ? Limit 1
`

func (q *Queries) GetMacroDetails(ctx context.Context, macrono int64) (MacroDetail, error) {
	row := q.db.QueryRowContext(ctx, getMacroDetails, macrono)
	var i MacroDetail
	err := row.Scan(&i.MacroNo, &i.Details)
	return i, err
}

const getMacroNoBasedOnType = `-- name: GetMacroNoBasedOnType :many
;

Select "MacroNo" from "MacroAddresses" where "NoOfCommands" = ?
`

func (q *Queries) GetMacroNoBasedOnType(ctx context.Context, noofcommands int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getMacroNoBasedOnType, noofcommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var MacroNo int64
		if err := rows.Scan(&MacroNo); err != nil {
			return nil, err
		}
		items = append(items, MacroNo)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMacroTypeBasedOnNumber = `-- name: GetMacroTypeBasedOnNumber :one
Select "NoOfCommands" from "MacroAddresses" where "MacroNo" = ?
`

func (q *Queries) GetMacroTypeBasedOnNumber(ctx context.Context, macrono int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMacroTypeBasedOnNumber, macrono)
	var NoOfCommands int64
	err := row.Scan(&NoOfCommands)
	return NoOfCommands, err
}

const getMacroTypes = `-- name: GetMacroTypes :many
Select Distinct "NoOfCommands" from "MacroAddresses"
`

func (q *Queries) GetMacroTypes(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getMacroTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var NoOfCommands int64
		if err := rows.Scan(&NoOfCommands); err != nil {
			return nil, err
		}
		items = append(items, NoOfCommands)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMappedMacroCommands = `-- name: GetMappedMacroCommands :many
Select ID, MacroUpdate, DatasetUpdate, MacroEnable, MacroInit, MasterMacroEnable from "MacroRelatedTCs"
`

func (q *Queries) GetMappedMacroCommands(ctx context.Context) ([]MacroRelatedTC, error) {
	rows, err := q.db.QueryContext(ctx, getMappedMacroCommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MacroRelatedTC
	for rows.Next() {
		var i MacroRelatedTC
		if err := rows.Scan(
			&i.ID,
			&i.MacroUpdate,
			&i.DatasetUpdate,
			&i.MacroEnable,
			&i.MacroInit,
			&i.MasterMacroEnable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedMacroNos = `-- name: GetSavedMacroNos :many
Select "MacroNo"  from "MacroDetails"
`

func (q *Queries) GetSavedMacroNos(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getSavedMacroNos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var MacroNo int64
		if err := rows.Scan(&MacroNo); err != nil {
			return nil, err
		}
		items = append(items, MacroNo)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeDatasetAddresses = `-- name: StoreDatasetAddresses :exec
Insert into "DatasetAddresses" 
("DatasetNo", "NoOfCommands", "Address") 
values 
(?, ?, ?)
`

type StoreDatasetAddressesParams struct {
	DatasetNo    int64
	NoOfCommands int64
	Address      int64
}

func (q *Queries) StoreDatasetAddresses(ctx context.Context, arg StoreDatasetAddressesParams) error {
	_, err := q.db.ExecContext(ctx, storeDatasetAddresses, arg.DatasetNo, arg.NoOfCommands, arg.Address)
	return err
}

const storeDatasetDetails = `-- name: StoreDatasetDetails :exec
Insert into "DatasetDetails" 
("DatasetNo", "Details", "LinkedMacro", "Description") 
values 
(?, ?, ?, ?)
`

type StoreDatasetDetailsParams struct {
	DatasetNo   int64
	Details     string
	LinkedMacro int64
	Description string
}

func (q *Queries) StoreDatasetDetails(ctx context.Context, arg StoreDatasetDetailsParams) error {
	_, err := q.db.ExecContext(ctx, storeDatasetDetails,
		arg.DatasetNo,
		arg.Details,
		arg.LinkedMacro,
		arg.Description,
	)
	return err
}

const storeMacroAddresses = `-- name: StoreMacroAddresses :exec
Insert into "MacroAddresses" 
("MacroNo", "NoOfCommands", "Address") 
values 
(?, ?, ?)
`

type StoreMacroAddressesParams struct {
	MacroNo      int64
	NoOfCommands int64
	Address      int64
}

func (q *Queries) StoreMacroAddresses(ctx context.Context, arg StoreMacroAddressesParams) error {
	_, err := q.db.ExecContext(ctx, storeMacroAddresses, arg.MacroNo, arg.NoOfCommands, arg.Address)
	return err
}

const storeMacroDetails = `-- name: StoreMacroDetails :exec
Insert into "MacroDetails" 
("MacroNo", "Details") 
values 
(?, ?)
`

type StoreMacroDetailsParams struct {
	MacroNo int64
	Details string
}

func (q *Queries) StoreMacroDetails(ctx context.Context, arg StoreMacroDetailsParams) error {
	_, err := q.db.ExecContext(ctx, storeMacroDetails, arg.MacroNo, arg.Details)
	return err
}

const storeMacroRelatedTCs = `-- name: StoreMacroRelatedTCs :exec
Update MacroRelatedTCs set
"MacroUpdate" = ?,
"DatasetUpdate" = ?,
"MacroEnable" = ?,
"MacroInit" = ?,
"MasterMacroEnable" = ?
`

type StoreMacroRelatedTCsParams struct {
	MacroUpdate       string
	DatasetUpdate     string
	MacroEnable       string
	MacroInit         string
	MasterMacroEnable string
}

func (q *Queries) StoreMacroRelatedTCs(ctx context.Context, arg StoreMacroRelatedTCsParams) error {
	_, err := q.db.ExecContext(ctx, storeMacroRelatedTCs,
		arg.MacroUpdate,
		arg.DatasetUpdate,
		arg.MacroEnable,
		arg.MacroInit,
		arg.MasterMacroEnable,
	)
	return err
}

const storeTelecommands = `-- name: StoreTelecommands :exec
Insert into "Telecommands" 
("CommandID", "Mnemonics", "Code", "Type") 
values 
(?, ?, ?, ?)
`

type StoreTelecommandsParams struct {
	CommandID string
	Mnemonics string
	Code      string
	Type      string
}

func (q *Queries) StoreTelecommands(ctx context.Context, arg StoreTelecommandsParams) error {
	_, err := q.db.ExecContext(ctx, storeTelecommands,
		arg.CommandID,
		arg.Mnemonics,
		arg.Code,
		arg.Type,
	)
	return err
}
